version: '3.7'

services:
  kafka:
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092

  segmentation-service:
    image: segmentation-service
    links:
      - kafka:kafka
    ports:
      - 5000:5000
