# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NewSegmentationIsReadyEvent.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='NewSegmentationIsReadyEvent.proto',
  package='ml4_segandrec_service',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!NewSegmentationIsReadyEvent.proto\x12\x15ml4_segandrec_service\"Q\n\x1bNewSegmentationIsReadyEvent\x12\x0e\n\x06wineId\x18\x03 \x01(\t\x12\x10\n\x08segmLink\x18\x01 \x01(\t\x12\x10\n\x08maskLink\x18\x02 \x01(\tb\x06proto3'
)




_NEWSEGMENTATIONISREADYEVENT = _descriptor.Descriptor(
  name='NewSegmentationIsReadyEvent',
  full_name='ml4_segandrec_service.NewSegmentationIsReadyEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='wineId', full_name='ml4_segandrec_service.NewSegmentationIsReadyEvent.wineId', index=0,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='segmLink', full_name='ml4_segandrec_service.NewSegmentationIsReadyEvent.segmLink', index=1,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='maskLink', full_name='ml4_segandrec_service.NewSegmentationIsReadyEvent.maskLink', index=2,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=141,
)

DESCRIPTOR.message_types_by_name['NewSegmentationIsReadyEvent'] = _NEWSEGMENTATIONISREADYEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NewSegmentationIsReadyEvent = _reflection.GeneratedProtocolMessageType('NewSegmentationIsReadyEvent', (_message.Message,), {
  'DESCRIPTOR' : _NEWSEGMENTATIONISREADYEVENT,
  '__module__' : 'NewSegmentationIsReadyEvent_pb2'
  # @@protoc_insertion_point(class_scope:ml4_segandrec_service.NewSegmentationIsReadyEvent)
  })
_sym_db.RegisterMessage(NewSegmentationIsReadyEvent)


# @@protoc_insertion_point(module_scope)